[project]
name = 'Decentralized-Food-Traceability-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.premium-origin-nft]
path = 'contracts/premium-origin-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
